

  async function hello() {
    const userName = document.getElementById('aiAgent').value.trim();
    if (!userName) {
      alert('Please enter your name.');
      return;
    }

    const outputArea = document.getElementById('outputArea');

    // ✨ Show loading spinner immediately
    outputArea.innerHTML = `
      <div class="flex justify-center items-center h-48">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-white"></div>
      </div>
    `;
  
  
    try {
      const res = await fetch('/hello', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ companyName: userName })  // you are sending companyName, it's okay
      });
      const data = await res.json();
  
      const agentName = data.todayPrediction.agent || 'Agent';
      const serviceName = data.todayPrediction.service || 'Service';
  
      document.getElementById('outputArea').innerHTML = `
        <div class="bg-white/20 p-6 rounded-xl text-center">
          <h2 class="text-2xl font-semibold mb-2">👋 Hello ${userName}!</h2>
          <p class="text-lg">I am <span class="font-bold">${agentName}</span>, and I will provide you <span class="font-bold">${serviceName}</span> service.</p>
        </div>
      `;
    } catch (error) {
      console.error(error);
      // alert('Failed to call AI Agent.');

      outputArea.innerHTML = `<p class="text-red-500 text-center">Failed to get hello messsage. Try again.</p>`;


    }
  }
  






  async function leo() {
    const movieName = document.getElementById('aiAgentLeo').value.trim();
    if (!movieName) {
      alert('Please enter your movie name.');
      return;
    }

    const outputArea = document.getElementById('outputArea');

    // ✨ Show loading spinner immediately
    outputArea.innerHTML = `
      <div class="flex justify-center items-center h-48">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-white"></div>
      </div>
    `;
  
    try {
      const res = await fetch('/leo', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ movieName })
      });
      const data = await res.json();
  
      const agentName = data.movieResult.agent || 'Agent';
      const synopsis = data.movieResult.synopsis || 'Synopsis not available.';
      const director = data.movieResult.director || 'Unknown Director';
      const cast = data.movieResult.cast || 'Unknown Cast';
      const verdict = data.movieResult.verdict || 'No Verdict';
      const releaseDate = data.movieResult.releaseDate || 'Unknown Date';
      const url = data.movieResult.url || '';
  
      document.getElementById('outputArea').innerHTML = `
        <div class="bg-white/20 p-6 rounded-3xl text-white text-center shadow-lg max-w-md mx-auto">
          ${url ? `<img src="${url}" alt="Movie Poster" class="rounded-2xl w-full h-full object-cover mb-6 shadow-md" />` : ''}
          <h2 class="text-4xl font-extrabold mb-4">${movieName}</h2>
          <p class="italic text-sm mb-6">"${synopsis}"</p>
  
          <div class="text-left space-y-2 text-md">
            <p><strong>🎬 Director:</strong> ${director}</p>
            <p><strong>🎥 Cast:</strong> ${cast}</p>
            <p><strong>📈 Verdict:</strong> ${verdict}</p>
            <p><strong>🗓️ Release Date:</strong> ${releaseDate}</p>
            <p>${url}</p>
          </div>
  
          <p class="mt-6 text-xs text-gray-300 italic">Generated by ${agentName}</p>
        </div>
      `;
    } catch (error) {
      console.error(error);
      // alert('Failed to call AI Agent.');

      outputArea.innerHTML = `<p class="text-red-500 text-center">Failed to load movie details. Try again.</p>`;

    }
  }
  
  
  

